name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore MachineMonitoring.sln

    - name: Setup SonarScanner for MSBuild
      uses: SonarSource/sonar-scanner-msbuild@v1.8.0

    - name: Begin SonarQube analysis
      run: |
        SonarScanner.MSBuild.exe begin /k:"MachineDowntimeMonitoring" /o:"YourOrganization" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: Build solution
      run: msbuild MachineMonitoring.sln /t:Rebuild

    - name: End SonarQube analysis
      run: |
        SonarScanner.MSBuild.exe end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
